// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3NPWlnRoSygv_ruc_2UzNKa7hbjT3i8c',
    appId: '1:631982115514:web:f5a0c4daf7f3bc559b1083',
    messagingSenderId: '631982115514',
    projectId: 'caregiver-app-fec3f',
    authDomain: 'caregiver-app-fec3f.firebaseapp.com',
    storageBucket: 'caregiver-app-fec3f.firebasestorage.app',
    measurementId: 'G-ERNWZ8NPN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUkid8i7DxdMoU58T7MlyScPKYsqSFnHA',
    appId: '1:631982115514:android:4fc6d18a6a1c8d3f9b1083',
    messagingSenderId: '631982115514',
    projectId: 'caregiver-app-fec3f',
    storageBucket: 'caregiver-app-fec3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-CC4vFaMmTZ4lrCHpatKswY3EOYIPoI',
    appId: '1:631982115514:ios:cb693c3c22fee1089b1083',
    messagingSenderId: '631982115514',
    projectId: 'caregiver-app-fec3f',
    storageBucket: 'caregiver-app-fec3f.firebasestorage.app',
    iosBundleId: 'com.example.caregiverApp',
  );
}
